### ISSUE TITLE
PR #3 was reported changed but changes don't appear in code

### ISSUE THREAD

**Issue by jonathan-short** [zanox/mod-kinesis#5]
PR #3 changed a log message from info to debug due to volume.  The PR was closed with a comment saying changed directly in the code, but the code does not appear to be changed: https://github.com/zanox/mod-kinesis/blob/master/src/main/java/com/zanox/vertx/mods/KinesisMessageProcessor.java#L173

**Comment by SaschaMoellering** [comment]
Sorry, my fault, fixed it in version 1.4.17.
